#!/usr/bin/env bash

socat TCP-LISTEN:8080,fork TCP:127.0.0.1:8000 &

if [ ! -f /var/datastore ]; then
  /gcd/gcd.sh create /var/datastore/
  cat > /var/datastore/WEB-INF/index.yaml << EOF
indexes:

# AUTOGENERATED
EOF
fi

/gcd/gcd.sh start -p 8000 /var/datastore/
